### ISSUE TITLE
Pip and Conda Package support

### ISSUE THREAD

**Issue by tvidano** [projectchrono/gym-chrono#2]
I love this idea of connect Project Chrono to Gym. However, I am having a difficult time compiling the PyChrono module. Could you create a pip package for the correct version of Chrono with its necessary modules? I am aware there is a conda release, but I don't think it was compiled with the correct Chrono modules. Maybe you can also create Gym-Chrono conda release as well?

Also creating a pip package might make this usable on Google's CoLab.

**Comment by Huzaifg** [comment]
Hello @tvidano

You are right in that the Chrono conda release is not up to date with gym-chrono. That being said, we are working on pushing a new conda pychrono package. This should be up in a few days. We are also working on a gym-chrono pip release. I suspect this to take about a month. 

However, I would still recommend building PyChrono from source, at least for the time being, since we have robot models in here that are not available in Chrono (the robot models are only available in a developer's fork of Chrono). Can you please post here the errors you face while building PyChrono from source?

**Comment by tvidano** [comment]
I resolved the issues. It was mostly due to my not having the correct shared libraries installed. So the resolution was just to find the right apt packages.
